### ISSUE TITLE
Is this working - any tutorial????

### ISSUE THREAD

**Issue by ghost** [MitkoTschimev/jsdoc-webpack-plugin#6]
I try to use it - and it seems to do nothing except of errors. 

See the simplest configuration - http://take.ms/Dyjjq.
Webpack config - http://take.ms/UAhIh.

**Comment by ashen9** [comment]
I have the same problem

**Comment by luckylooke** [comment]
It is working fine for me, do you have windows OS? Because I have made fix for windows [recently](https://github.com/tfiwm/jsdoc-webpack-plugin/pull/7). On Mac it already worked before.

**Comment by ghost** [comment]
Yes, I had this issue on Windows. Going to try you fix today.

**Comment by MitkoTschimev** [comment]
Fixed with https://github.com/tfiwm/jsdoc-webpack-plugin/pull/7
